doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      exemple_id: DoctrineTestingTools\Infrastructure\Types\ExempleIdType
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    auto_mapping: true
    mappings:
      Exemple:
        is_bundle: false
        type: xml
        dir: '%kernel.project_dir%/src/Infrastructure/Mapping'
        prefix: 'DoctrineTestingTools\Domain'
