services:
  dtt-php:
    container_name: "dtt-php"
    image: dtt-php:latest
    build:
      context: .
      dockerfile: php/Dockerfile
      tags:
        - latest
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/dtt"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    networks:
      - dtt-network

networks:
  dtt-network:
    driver: bridge
    name: dtt-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fd00:2:20::/112
          gateway: fd00:2:20::1

volumes:
  dtt-db:
